CREATE TABLE TB_CONSULTA (
    id SERIAL PRIMARY KEY,
    TB_PACIENTES BIGINT NOT NULL,
    TB_MEDICOS BIGINT NOT NULL,
    horario_consulta TIMESTAMP,

    CONSTRAINT fk_paciente
        FOREIGN KEY (TB_PACIENTES)
        REFERENCES TB_PACIENTES(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_medico
        FOREIGN KEY (TB_MEDICOS)
        REFERENCES TB_MEDICOS(id)
        ON DELETE CASCADE
);